name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
  markdownlint:
    name: MarkdownLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run MarkdownLint
        uses: nosborn/github-action-markdown-cli@v2.0.0
        with:
          files: .
          config_file: .markdownlint.yaml
  style-check:
    name: Style check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: ['3.7', '3.8', '3.9']
    container:
      image: python:${{ matrix.python }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          set -ex
          python -V
          pip install -U pip setuptools wheel
          pip install .[test]
      - name: Style check
        run: flake8 system
  type-check:
    name: Type check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: ['3.7', '3.8', '3.9']
    container:
      image: python:${{ matrix.python }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          set -ex
          python -V
          pip install -U pip setuptools wheel
          pip install .[typecheck]
      - name: Type check
        run: pytype system
  typeset-paper:
    name: Typeset paper
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Typeset paper
        run: latexmk -cd -pdf -shell-escape paper/main.tex
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: paper
          path: |
            paper/main.pdf
